### ISSUE TITLE
NumberPicker are misplaced

### ISSUE THREAD

**Issue by SimonMarquis** [foxykeep/LifeCounter#2]
I'm testing on a HTC One (xxhdpi) and the numberPickers are overlaying scores.
I think it's because of weights...
Is there a reason you are not using only a linearLayout with three children (+icon, textView, -icon) ?
![screenshot_2013-09-23-08-36-53](https://f.cloud.github.com/assets/1921278/1191095/c1c475b8-2447-11e3-8271-be1089fe10c6.png)

**Comment by foxykeep** [comment]
The problem is coming from the xxhdpi which is not behaving like the other density 9-patch. I'll check what's wrong with the assets.
Also need to get a hold of a xxhdpi device to test the fixed version of the asset ;)

**Comment by SimonMarquis** [comment]
I could test for you if you want to ;)

**Comment by foxykeep** [comment]
Fix is ready. It'll be in the next release. Need to finish some other stuff first to finish this release
