### ISSUE TITLE
Switch license to 0BSD

### ISSUE THREAD

**Issue by stokito** [foxykeep/LifeCounter#4]
The Beerware license has some problems and it would be great if you can relicense under the 0BSD which is reviewed and approved by OSI.

**Comment by foxykeep** [comment]
What are the problems with the beer ware license ?

**Comment by stokito** [comment]
Sorry, I just used a Github search by the Beerware license and your project was the only that I found. Nothing really wrong with it but it's usage increases fragmentation of licenses which leads to real problems when developers don't sure if they can improve it and users are not sure if this is a FOSS. At least they have to spent their time to learn about the license: "Is it legally correct? Can I use it? Is it a serious app or internally it's also a joke" etc.
But also by using standard well known licenses you make more people familiar with them and on the next project someone may take the same license as in your project.

A [quote from reddit](https://www.reddit.com/r/programming/comments/6v66l/beerware_the_best_opensource_license_ive_ever_seen/):

> I see that you are not a professional programmer. It's not about being "anal".
> 
> Think of it like this: you rent a car. Just as you begin to sign the rental agreement, you notice a small binder of additional agreements that you have to make. You discover that, while you can use the engine for whatever purpose you like, you can't use the transmission outside the country of Germany, the wheel manufacturer demands postcards, the glove compartment guy wants beer, the person who made the dashboard insists that no military person should ever be allowed to use his equipment, the guy who made the seats is against using the car for commercial purposes, and the people who made the airbag don't seem to have made any provisions for licensing whatsoever, so even if they deploy by themselves, you might get sued for using them.
> 
> And this isn't just a disease of capitalism -- the same problem occurs even with software that the authors intended to be freely used. So many of them put so much effort into that goal, only to screw it all up with a joke license.
> 

I'll close the issue, sorry for annoying.
